Repository SDOS2020/Team_1_Business_Coaching_Platform, pull requests merged in 2020-12, with the labels that each got.

#19 Anmol homepage
  Business_Coaching_Platform/home/static/home/main.css
  Business_Coaching_Platform/home/templates/home/base.html
  Business_Coaching_Platform/home/templates/home/home.html
  Business_Coaching_Platform/user/templates/user/login.html
  Business_Coaching_Platform/user/templates/user/profile_coach.html
  Business_Coaching_Platform/user/templates/user/register_coach.html
  Business_Coaching_Platform/user/templates/user/register_coachee.html
Labels: enhancement: high

#25 Shreyansh chat
  Business_Coaching_Platform/Business_Coaching_Platform/settings.py
  Business_Coaching_Platform/dashboard/static/dashboard/components/chat_box.js
  Business_Coaching_Platform/dashboard/static/dashboard/components/connection_list.js
  Business_Coaching_Platform/dashboard/templates/dashboard/chat.html
  Business_Coaching_Platform/enrolment/templates/enrolment/find_coach.html
  Business_Coaching_Platform/notification/routing.py
  Business_Coaching_Platform/user/serializer.py
  Business_Coaching_Platform/user/templates/user/profile_coach_view.html
Labels: enhancement: medium

#29 Find coach tab added in nav bar
  .gitignore
  Business_Coaching_Platform/dashboard/templates/dashboard/coach_dashboard.html
  Business_Coaching_Platform/enrolment/templates/enrolment/find_coach.html
  Business_Coaching_Platform/enrolment/urls.py
  Business_Coaching_Platform/enrolment/views.py
  Business_Coaching_Platform/home/templates/home/base.html
Labels: enhancement: low

#37 Add Notification and Bug fixes
  Business_Coaching_Platform/Business_Coaching_Platform/urls.py
  Business_Coaching_Platform/dashboard/signals.py
  Business_Coaching_Platform/dashboard/static/dashboard/components/chat_box.js
  Business_Coaching_Platform/dashboard/static/dashboard/components/notification_panel.js
  Business_Coaching_Platform/dashboard/static/dashboard/notification_style.css
  Business_Coaching_Platform/dashboard/templates/dashboard/coach_dashboard.html
  Business_Coaching_Platform/dashboard/templates/dashboard/coachee_dashboard.html
  Business_Coaching_Platform/notification/admin.py
  Business_Coaching_Platform/notification/models.py
  Business_Coaching_Platform/notification/serializer.py
  Business_Coaching_Platform/notification/signals.py
  Business_Coaching_Platform/notification/templates/notification/room.html
  Business_Coaching_Platform/notification/urls.py
  Business_Coaching_Platform/notification/views.py
  Business_Coaching_Platform/user/forms.py
Labels: enhancement: medium

#47 Schedule Meeting and Calendly enrol (Book a free session)
  Business_Coaching_Platform/dashboard/static/dashboard/components/connection_list.js
  Business_Coaching_Platform/dashboard/templates/dashboard/coach_dashboard.html
  Business_Coaching_Platform/user/templates/user/profile_coach_view.html
Labels: enhancement: high

#49 Add email functionality
  Business_Coaching_Platform/Business_Coaching_Platform/settings.py
  Business_Coaching_Platform/dashboard/static/dashboard/components/notification_panel.js
  Business_Coaching_Platform/dedicated_page/apps.py
  Business_Coaching_Platform/dedicated_page/signals.py
  Business_Coaching_Platform/notification/views.py
Labels: enhancement: high

#52 Anmol - Minor enhancements and bug fixes
  Business_Coaching_Platform/Business_Coaching_Platform/settings.py
  Business_Coaching_Platform/dashboard/templates/dashboard/coach_dashboard.html
  Business_Coaching_Platform/dedicated_page/models.py
  Business_Coaching_Platform/enrolment/templates/enrolment/find_coach.html
  Business_Coaching_Platform/home/static/home/psy.jpeg
  Business_Coaching_Platform/home/templates/home/home.html
  Business_Coaching_Platform/user/forms.py
  Business_Coaching_Platform/user/models.py
  Business_Coaching_Platform/user/serializer.py
  Business_Coaching_Platform/user/templates/user/change_password.html
  Business_Coaching_Platform/user/templates/user/profile_coach.html
  Business_Coaching_Platform/user/templates/user/profile_coach_view.html
  Business_Coaching_Platform/user/templates/user/profile_coachee.html
  Business_Coaching_Platform/user/templates/user/register_coach.html
  Business_Coaching_Platform/user/templates/user/update_coach.html
  Business_Coaching_Platform/user/templates/user/update_coachee.html
  Business_Coaching_Platform/user/urls.py
  Business_Coaching_Platform/user/views.py
Labels: enhancement: medium
